<?php

declare(strict_types=1);
namespace OCA\MaintenanceTracker\Db;
use OCP\DB\QueryBuilder\IQueryBuilder; use OCP\IDBConnection;
final class ActivityMeterMapper { public function __construct(private IDBConnection $db){}
 public function append(ActivityMeter $r):ActivityMeter{$q=$this->db->getQueryBuilder();$q->insert('maint_activity_meters')->values(['workspace_id'=>$q->createNamedParameter($r->getWorkspaceId(),IQueryBuilder::PARAM_INT),'activity_id'=>$q->createNamedParameter($r->getActivityId(),IQueryBuilder::PARAM_INT),'uuid'=>$q->createNamedParameter($r->getUuid(),IQueryBuilder::PARAM_STR),'position'=>$q->createNamedParameter($r->getPosition(),IQueryBuilder::PARAM_INT),'meter_id'=>$q->createNamedParameter($r->getMeterId(),IQueryBuilder::PARAM_INT),'meter_uuid'=>$q->createNamedParameter($r->getMeterUuid(),IQueryBuilder::PARAM_STR),'meter_name'=>$q->createNamedParameter($r->getMeterName(),IQueryBuilder::PARAM_STR),'reading_id'=>$q->createNamedParameter($r->getReadingId(),IQueryBuilder::PARAM_INT),'reading_uuid'=>$q->createNamedParameter($r->getReadingUuid(),IQueryBuilder::PARAM_STR),'observed_at'=>$q->createNamedParameter($r->getObservedAt(),IQueryBuilder::PARAM_INT),'canonical_value'=>$q->createNamedParameter($r->getCanonicalValue(),IQueryBuilder::PARAM_INT),'original_value'=>$q->createNamedParameter($r->getOriginalValue(),IQueryBuilder::PARAM_STR),'original_unit'=>$q->createNamedParameter($r->getOriginalUnit(),IQueryBuilder::PARAM_STR)]);$q->executeStatement();$r->setId($q->getLastInsertId());return $r;}
 /** @return list<ActivityMeter> */ public function findForActivity(int $ws,int $activityId):array{$q=$this->db->getQueryBuilder();$q->select('*')->from('maint_activity_meters')->where($q->expr()->eq('workspace_id',$q->createNamedParameter($ws,IQueryBuilder::PARAM_INT)))->andWhere($q->expr()->eq('activity_id',$q->createNamedParameter($activityId,IQueryBuilder::PARAM_INT)))->orderBy('position','ASC');$res=$q->executeQuery();$out=[];try{while(($x=$res->fetchAssociative())!==false){$r=new ActivityMeter();$r->setId((int)$x['id']);$r->setWorkspaceId((int)$x['workspace_id']);$r->setActivityId((int)$x['activity_id']);$r->setUuid((string)$x['uuid']);$r->setPosition((int)$x['position']);$r->setMeterId((int)$x['meter_id']);$r->setMeterUuid((string)$x['meter_uuid']);$r->setMeterName((string)$x['meter_name']);$r->setReadingId((int)$x['reading_id']);$r->setReadingUuid((string)$x['reading_uuid']);$r->setObservedAt((int)$x['observed_at']);$r->setCanonicalValue((int)$x['canonical_value']);$r->setOriginalValue((string)$x['original_value']);$r->setOriginalUnit((string)$x['original_unit']);$out[]=$r;}}finally{$res->closeCursor();}return $out;}
}
