<?php

declare(strict_types=1);
namespace OCA\MaintenanceTracker\Db;
use OCP\AppFramework\Db\DoesNotExistException; use OCP\DB\QueryBuilder\IQueryBuilder; use OCP\IDBConnection;
final class ActivityItemMapper { public function __construct(private IDBConnection $db){}
 public function append(ActivityItem $r):ActivityItem{$q=$this->db->getQueryBuilder();$q->insert('maint_activity_items')->values(['workspace_id'=>$q->createNamedParameter($r->getWorkspaceId(),IQueryBuilder::PARAM_INT),'activity_id'=>$q->createNamedParameter($r->getActivityId(),IQueryBuilder::PARAM_INT),'uuid'=>$q->createNamedParameter($r->getUuid(),IQueryBuilder::PARAM_STR),'position'=>$q->createNamedParameter($r->getPosition(),IQueryBuilder::PARAM_INT),'definition_id'=>$this->n($q,$r->getDefinitionId()),'definition_uuid'=>$this->s($q,$r->getDefinitionUuid()),'component_id'=>$this->n($q,$r->getComponentId()),'component_uuid'=>$this->s($q,$r->getComponentUuid()),'component_name'=>$this->s($q,$r->getComponentName()),'title'=>$q->createNamedParameter($r->getTitle(),IQueryBuilder::PARAM_STR),'kind'=>$q->createNamedParameter($r->getKind(),IQueryBuilder::PARAM_STR),'notes'=>$this->s($q,$r->getNotes())]);$q->executeStatement();$r->setId($q->getLastInsertId());return $r;}
 /** @return list<ActivityItem> */ public function findForActivity(int $ws,int $activityId):array{$q=$this->db->getQueryBuilder();$q->select('*')->from('maint_activity_items')->where($q->expr()->eq('workspace_id',$q->createNamedParameter($ws,IQueryBuilder::PARAM_INT)))->andWhere($q->expr()->eq('activity_id',$q->createNamedParameter($activityId,IQueryBuilder::PARAM_INT)))->orderBy('position','ASC');return $this->many($q);}
 private function many($q):array{$res=$q->executeQuery();$out=[];try{while(($row=$res->fetchAssociative())!==false)$out[]=$this->hydrate($row);}finally{$res->closeCursor();}return $out;}
 private function hydrate(array $x):ActivityItem{$r=new ActivityItem();$r->setId((int)$x['id']);$r->setWorkspaceId((int)$x['workspace_id']);$r->setActivityId((int)$x['activity_id']);$r->setUuid((string)$x['uuid']);$r->setPosition((int)$x['position']);$r->setDefinitionId($x['definition_id']===null?null:(int)$x['definition_id']);$r->setDefinitionUuid($x['definition_uuid']===null?null:(string)$x['definition_uuid']);$r->setComponentId($x['component_id']===null?null:(int)$x['component_id']);$r->setComponentUuid($x['component_uuid']===null?null:(string)$x['component_uuid']);$r->setComponentName($x['component_name']===null?null:(string)$x['component_name']);$r->setTitle((string)$x['title']);$r->setKind((string)$x['kind']);$r->setNotes($x['notes']===null?null:(string)$x['notes']);return $r;}
 private function s($q,?string $v){return $q->createNamedParameter($v,$v===null?IQueryBuilder::PARAM_NULL:IQueryBuilder::PARAM_STR);} private function n($q,?int $v){return $q->createNamedParameter($v,$v===null?IQueryBuilder::PARAM_NULL:IQueryBuilder::PARAM_INT);}
}
