<?php

declare(strict_types=1);
namespace OCA\MaintenanceTracker\Controller;
use OCA\MaintenanceTracker\Exception\{AccessDeniedException,NotFoundException,RevisionConflictException,ValidationException};use OCA\MaintenanceTracker\Service\{ActivityService,AuthorizationCatalog,CurrentUser,WorkspaceService};use OCP\AppFramework\Http;use OCP\AppFramework\Http\Attribute\{ApiRoute,NoAdminRequired};use OCP\AppFramework\Http\DataResponse;use OCP\AppFramework\OCS\{OCSBadRequestException,OCSForbiddenException,OCSNotFoundException,OCSPreconditionFailedException};use OCP\AppFramework\OCSController;use OCP\IRequest;
final class ActivityController extends OCSController {public function __construct(string $appName,IRequest $request,private CurrentUser $currentUser,private WorkspaceService $workspaces,private ActivityService $service){parent::__construct($appName,$request);}
 #[NoAdminRequired] #[ApiRoute(verb:'GET',url:'/api/v1/assets/{assetUuid}/activities')] public function index(string $assetUuid,?string $workspace=null):DataResponse{return $this->run(fn($c)=>new DataResponse(['workspace'=>$c->workspace()->getUuid(),'items'=>$this->service->list($c,$assetUuid)]),$workspace,AuthorizationCatalog::ACTIVITY_READ);}
 #[NoAdminRequired] #[ApiRoute(verb:'GET',url:'/api/v1/activities/{uuid}')] public function show(string $uuid,?string $workspace=null):DataResponse{return $this->run(fn($c)=>new DataResponse($this->service->show($c,$uuid)),$workspace,AuthorizationCatalog::ACTIVITY_READ);}
 #[NoAdminRequired] #[ApiRoute(verb:'POST',url:'/api/v1/assets/{assetUuid}/activities')] public function create(string $assetUuid,array $activity,?string $workspace=null):DataResponse{return $this->run(fn($c)=>new DataResponse($this->service->create($c,$assetUuid,$activity),Http::STATUS_CREATED),$workspace,AuthorizationCatalog::ACTIVITY_CREATE);}
 #[NoAdminRequired] #[ApiRoute(verb:'PATCH',url:'/api/v1/activities/{uuid}')] public function update(string $uuid,int $expectedRevision,array $activity,?string $workspace=null):DataResponse{return $this->run(fn($c)=>new DataResponse($this->service->update($c,$uuid,$expectedRevision,$activity)),$workspace,AuthorizationCatalog::ACTIVITY_MANAGE);}
 #[NoAdminRequired] #[ApiRoute(verb:'DELETE',url:'/api/v1/activities/{uuid}')] public function destroy(string $uuid,int $expectedRevision,?string $workspace=null):DataResponse{return $this->run(fn($c)=>new DataResponse($this->service->archive($c,$uuid,$expectedRevision)),$workspace,AuthorizationCatalog::ACTIVITY_MANAGE);}
 private function run(callable $op,?string $workspace,string $cap):DataResponse{try{return $this->workspaces->runWithCapability($this->currentUser->uid(),$workspace,$cap,$op);}catch(AccessDeniedException $e){throw new OCSForbiddenException($e->getMessage(),$e);}catch(NotFoundException $e){throw new OCSNotFoundException($e->getMessage(),$e);}catch(ValidationException $e){throw new OCSBadRequestException($e->getMessage(),$e);}catch(RevisionConflictException $e){throw new OCSPreconditionFailedException($e->getMessage(),$e);}}
}
