<?php

declare(strict_types=1);

/**
 * SPDX-FileCopyrightText: 2026 Alan Johnson
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
namespace OCA\MaintenanceTracker\Controller;
use OCA\MaintenanceTracker\Exception\AccessDeniedException;use OCA\MaintenanceTracker\Exception\NotFoundException;use OCA\MaintenanceTracker\Exception\ValidationException;use OCA\MaintenanceTracker\Service\ComponentService;use OCA\MaintenanceTracker\Service\CurrentUser;use OCA\MaintenanceTracker\Service\WorkspaceService;use OCP\AppFramework\Http;use OCP\AppFramework\Http\Attribute\ApiRoute;use OCP\AppFramework\Http\Attribute\NoAdminRequired;use OCP\AppFramework\Http\DataResponse;use OCP\AppFramework\OCS\OCSBadRequestException;use OCP\AppFramework\OCS\OCSForbiddenException;use OCP\AppFramework\OCS\OCSNotFoundException;use OCP\AppFramework\OCSController;use OCP\IRequest;
final class ComponentController extends OCSController{public function __construct(string $appName,IRequest $request,private CurrentUser $user,private WorkspaceService $workspaces,private ComponentService $service){parent::__construct($appName,$request);}#[NoAdminRequired]#[ApiRoute(verb:'GET',url:'/api/v1/assets/{assetUuid}/components')]public function index(string $assetUuid,?string $workspace=null):DataResponse{try{return $this->workspaces->runWithCapability($this->user->uid(),$workspace,'inventory.read',fn($c)=>new DataResponse(['items'=>$this->service->list($c,$assetUuid)]));}catch(AccessDeniedException $e){throw new OCSForbiddenException($e->getMessage(),$e);}catch(NotFoundException $e){throw new OCSNotFoundException($e->getMessage(),$e);}}#[NoAdminRequired]#[ApiRoute(verb:'POST',url:'/api/v1/assets/{assetUuid}/components')]public function create(string $assetUuid,array $component,?string $workspace=null):DataResponse{try{return $this->workspaces->runWithCapability($this->user->uid(),$workspace,'inventory.manage',fn($c)=>new DataResponse($this->service->create($c,$assetUuid,$component)->toApi($component['parentUuid']??null),Http::STATUS_CREATED));}catch(AccessDeniedException $e){throw new OCSForbiddenException($e->getMessage(),$e);}catch(NotFoundException $e){throw new OCSNotFoundException($e->getMessage(),$e);}catch(ValidationException $e){throw new OCSBadRequestException($e->getMessage(),$e);}}}
