<?php

declare(strict_types=1);

/**
 * SPDX-FileCopyrightText: 2026 Alan Johnson
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
namespace OCA\MaintenanceTracker\Service;
use OCA\MaintenanceTracker\Db\Asset;use OCA\MaintenanceTracker\Db\Component;use OCA\MaintenanceTracker\Db\ComponentMapper;use OCA\MaintenanceTracker\Exception\NotFoundException;use OCA\MaintenanceTracker\Exception\ValidationException;use OCA\MaintenanceTracker\Model\WorkspaceContext;use OCP\IDBConnection;use OCP\AppFramework\Db\DoesNotExistException;use OCP\AppFramework\Utility\ITimeFactory;
final class ComponentService{
 public function __construct(private AssetService $assetService,private ComponentMapper $mapper,private UuidGenerator $uuidGenerator,private ChangeJournal $journal,private IDBConnection $db,private ITimeFactory $timeFactory){}
 public function list(WorkspaceContext $c,string $assetUuid):array{$asset=$this->assetService->find($c,$assetUuid);$rows=$this->mapper->findForAsset($c->workspace()->getId(),$asset->getId());$byId=[];foreach($rows as $r){$byId[$r->getId()]=$r->getUuid();}return array_map(fn(Component $r)=>$r->toApi($r->getParentId()===null?null:($byId[$r->getParentId()]??null)),$rows);}
 public function create(WorkspaceContext $c,string $assetUuid,array $input):Component{$asset=$this->assetService->find($c,$assetUuid);$v=$this->validate($input,true);$parentId=null;if($v['parentUuid']!==null){$p=$this->find($c,$v['parentUuid']);if($p->getAssetId()!==$asset->getId())throw new ValidationException('parentUuid must belong to the same asset');$parentId=$p->getId();}$now=$this->timeFactory->getTime();$r=new Component();$r->setWorkspaceId($c->workspace()->getId());$r->setAssetId($asset->getId());$r->setParentId($parentId);$r->setUuid($v['uuid']??$this->uuidGenerator->generate());$r->setTypeKey($v['type']);$r->setName($v['name']);$r->setManufacturer($v['manufacturer']);$r->setModel($v['model']);$r->setPartNumber($v['partNumber']);$r->setSerialNumber($v['serialNumber']);$r->setNotes($v['notes']);$r->setStatus($v['status']);$r->setRevision(1);$r->setCreatedAt($now);$r->setUpdatedAt($now);$r->setDeletedAt(null);$owns=!$this->db->inTransaction();if($owns)$this->db->beginTransaction();try{$r=$this->mapper->insert($r);$this->journal->record($r->getWorkspaceId(),'component',$r->getUuid(),'upsert',1,$now);if($owns)$this->db->commit();return $r;}catch(\Throwable $e){if($owns&&$this->db->inTransaction())$this->db->rollBack();throw $e;}}
 public function find(WorkspaceContext $c,string $uuid):Component{try{return $this->mapper->findByUuid($c->workspace()->getId(),strtolower($uuid));}catch(DoesNotExistException){throw new NotFoundException('Component not found');}}
 public function findById(WorkspaceContext $c,int $id,bool $includeDeleted=false):Component{try{return $this->mapper->findById($c->workspace()->getId(),$id,$includeDeleted);}catch(DoesNotExistException){throw new NotFoundException('Component not found');}}
 private function validate(array $in,bool $create):array{$allowed=['uuid','parentUuid','type','name','manufacturer','model','partNumber','serialNumber','notes','status'];$u=array_diff(array_keys($in),$allowed);if($u!==[])throw new ValidationException('Unknown component fields: '.implode(', ',$u));if($create&&!array_key_exists('name',$in))throw new ValidationException('The component name is required');return ['uuid'=>$this->uuid($in['uuid']??null),'parentUuid'=>$this->uuid($in['parentUuid']??null),'type'=>$this->key($in['type']??'component','type'),'name'=>$this->text($in['name']??null,'name',255,false),'manufacturer'=>$this->text($in['manufacturer']??null,'manufacturer',255,false,true),'model'=>$this->text($in['model']??null,'model',255,false,true),'partNumber'=>$this->text($in['partNumber']??null,'partNumber',255,false,true),'serialNumber'=>$this->text($in['serialNumber']??null,'serialNumber',255,false,true),'notes'=>$this->text($in['notes']??null,'notes',20000,true,true),'status'=>$this->status($in['status']??'active')];}
 private function uuid(mixed $v):?string{if($v===null||$v==='')return null;if(!is_string($v)||!UuidGenerator::isValid(strtolower(trim($v))))throw new ValidationException('UUID fields must be RFC 4122 version 4 UUIDs');return strtolower(trim($v));}
 private function key(mixed $v,string $f):string{$s=$this->text($v,$f,64,false);if(preg_match('/^[a-z0-9][a-z0-9_-]*$/D',$s)!==1)throw new ValidationException("{$f} must be a lowercase key");return $s;}
 private function status(mixed $v):string{$s=$this->text($v,'status',16,false);if(!in_array($s,['active','suppressed','retired'],true))throw new ValidationException('Unsupported component status');return $s;}
 private function text(mixed $v,string $f,int $m,bool $nl,bool $opt=false):?string{if($opt&&($v===null||$v===''))return null;if(!is_string($v))throw new ValidationException("{$f} must be a string");$v=trim($v);if($v===''&&!$opt)throw new ValidationException("{$f} cannot be empty");if(mb_strlen($v)>$m)throw new ValidationException("{$f} exceeds {$m} characters");$p=$nl?'/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/u':'/[\x00-\x1F\x7F]/u';if(preg_match($p,$v)===1)throw new ValidationException("{$f} contains unsupported control characters");return $v===''?null:$v;}
}
